apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uraxlaw.fullname" . }}-env
  labels:
    {{- include "uraxlaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "uraxlaw.envContent" . | nindent 4 }}
